function usage(choice, kindZh, meaningZh, example, kindJa, meaningJa) {
  return {
    zh: `「${choice}」正確用法：${kindZh}，意思係「${meaningZh}」。正確例子：${example}`,
    ja: `「${choice}」の正しい使い方：${kindJa}で、「${meaningJa}」という意味です。正しい例：${example}`
  };
}

const USAGE_BY_CHOICE = {
  "although": usage("although", "連接詞，後面接完整句子", "雖然", "Although it rained, the event continued.", "接続詞、後ろに文を置く", "〜だけれども"),
  "among": usage("among", "介系詞，用於三個或以上的人／物之中", "在...之中", "The files were shared among the team members.", "前置詞、3つ以上の中で使う", "〜の間で"),
  "are": usage("are", "be 動詞現在式，用於複數主詞或 you", "是／在", "The documents are ready.", "be動詞の現在形、複数主語や you に使う", "〜です／〜にあります"),
  "arrival": usage("arrival", "名詞", "到達", "The arrival time is 3 p.m.", "名詞", "到着"),
  "arrive": usage("arrive", "動詞原形", "到達", "Please arrive before 9 a.m.", "動詞の原形", "到着する"),
  "arrived": usage("arrived", "過去式／過去分詞", "已到達", "The package arrived yesterday.", "過去形・過去分詞", "到着した"),
  "arriving": usage("arriving", "現在分詞／動名詞", "正在到達／到達這件事", "Guests arriving late should call the front desk.", "現在分詞・動名詞", "到着している／到着すること"),
  "as soon as": usage("as soon as", "連接詞片語，後面接完整句子", "一...就...", "Please call me as soon as you arrive.", "接続詞句、後ろに文を置く", "〜するとすぐに"),
  "at": usage("at", "介系詞，用於具體時間點或地點點位", "在", "The meeting starts at 9 a.m.", "前置詞、時刻や地点に使う", "〜に／〜で"),
  "automate": usage("automate", "動詞原形", "使自動化", "The system can automate the task.", "動詞の原形", "自動化する"),
  "automatic": usage("automatic", "形容詞", "自動的", "The door has an automatic lock.", "形容詞", "自動の"),
  "automatically": usage("automatically", "副詞", "自動地", "The lights turn off automatically.", "副詞", "自動的に"),
  "automation": usage("automation", "名詞", "自動化", "Automation saves time.", "名詞", "自動化"),
  "avail": usage("avail", "動詞／名詞，商務英文較少見", "有幫助／效用", "The coupon will avail customers of a discount.", "動詞・名詞、ビジネス英語ではやや少ない", "役立つ／効用"),
  "availability": usage("availability", "名詞", "可用性／有空／有貨", "Please check the room availability.", "名詞", "利用可能性／空き状況"),
  "available": usage("available", "形容詞", "可用的／有空的／有貨的", "The meeting room is available now.", "形容詞", "利用可能な／空いている"),
  "availably": usage("availably", "少見副詞，實用英文通常改用 available", "可用地", "The documents are available online.", "まれな副詞で、通常は available を使う", "利用可能な形で"),
  "be": usage("be", "be 動詞原形", "是／成為／處於", "The file must be ready by noon.", "be動詞の原形", "〜である"),
  "because": usage("because", "連接詞，後面接完整句子", "因為", "The delivery was delayed because the road was closed.", "接続詞、後ろに文を置く", "なぜなら"),
  "because of": usage("because of", "介系詞片語，後面接名詞", "因為", "The event was canceled because of heavy rain.", "前置詞句、後ろに名詞を置く", "〜のために"),
  "before": usage("before", "連接詞／介系詞", "在...之前", "Please read the instructions before using the device.", "接続詞・前置詞", "〜の前に"),
  "began": usage("began", "begin 的過去式", "開始了", "The meeting began at 10 a.m.", "begin の過去形", "始まった"),
  "begin": usage("begin", "動詞原形", "開始", "The session will begin at noon.", "動詞の原形", "始まる"),
  "beginning": usage("beginning", "現在分詞／介系詞用法", "開始／從...開始", "Beginning next month, fees will increase.", "現在分詞・前置詞的用法", "始まり／〜から"),
  "begins": usage("begins", "第三人稱單數現在式", "開始", "The class begins at 9 a.m.", "三人称単数の現在形", "始まる"),
  "being": usage("being", "be 的現在分詞／動名詞", "正在被／存在", "The room is being cleaned.", "be の現在分詞・動名詞", "〜されている最中"),
  "beside": usage("beside", "介系詞", "在...旁邊", "The printer is beside the desk.", "前置詞", "〜のそばに"),
  "between": usage("between", "介系詞，常用於兩者之間或 between A and B", "在...之間", "The office is between the bank and the cafe.", "前置詞、between A and B で使う", "〜の間に"),
  "by": usage("by", "介系詞，用於期限或方法", "不遲於／透過", "Please submit the report by Friday.", "前置詞、期限や手段に使う", "〜までに／〜によって"),
  "clear": usage("clear", "形容詞／動詞原形", "清楚的／清除", "The instructions are clear.", "形容詞・動詞の原形", "明確な／片付ける"),
  "clearer": usage("clearer", "比較級形容詞", "更清楚", "This manual is clearer than the old one.", "比較級の形容詞", "より明確な"),
  "clearest": usage("clearest", "最高級形容詞", "最清楚", "This is the clearest explanation.", "最上級の形容詞", "最も明確な"),
  "clearly": usage("clearly", "副詞", "清楚地", "Please explain the policy clearly.", "副詞", "明確に"),
  "close": usage("close", "形容詞／動詞原形", "近的／關閉", "The hotel is close to the station.", "形容詞・動詞の原形", "近い／閉める"),
  "closely": usage("closely", "副詞", "仔細地／緊密地", "Please read the contract closely.", "副詞", "注意深く／密接に"),
  "closer": usage("closer", "比較級形容詞", "更近", "The new office is closer to the station.", "比較級の形容詞", "より近い"),
  "closest": usage("closest", "最高級形容詞", "最近", "This is the closest hotel to the airport.", "最上級の形容詞", "最も近い"),
  "complete": usage("complete", "形容詞／動詞原形", "完整的／完成", "Please complete the form today.", "形容詞・動詞の原形", "完全な／完了する"),
  "completed": usage("completed", "過去式／過去分詞／形容詞", "已完成", "The report was completed yesterday.", "過去形・過去分詞・形容詞", "完了した"),
  "completely": usage("completely", "副詞", "完全地", "The form must be filled out completely.", "副詞", "完全に"),
  "completion": usage("completion", "名詞", "完成", "The completion date is Friday.", "名詞", "完了"),
  "delivered": usage("delivered", "過去式／過去分詞", "已送達／被送達", "The package was delivered this morning.", "過去形・過去分詞", "配達された"),
  "delivers": usage("delivers", "第三人稱單數現在式", "配送", "The supplier delivers products every Monday.", "三人称単数の現在形", "配達する"),
  "depart": usage("depart", "動詞原形", "出發／離開", "The train will depart at noon.", "動詞の原形", "出発する"),
  "departed": usage("departed", "過去式／過去分詞／形容詞", "已離開的", "The train departed at noon.", "過去形・過去分詞・形容詞", "出発した"),
  "department": usage("department", "名詞", "部門", "Please contact the HR department.", "名詞", "部署"),
  "departmental": usage("departmental", "形容詞", "部門的", "The manager reviewed the departmental budget.", "形容詞", "部署の"),
  "despite": usage("despite", "介系詞，後面接名詞／動名詞", "儘管", "Despite the delay, the team finished the work.", "前置詞、後ろに名詞や動名詞を置く", "〜にもかかわらず"),
  "due to": usage("due to", "介系詞片語，後面接名詞", "因為", "The office is closed due to renovations.", "前置詞句、後ろに名詞を置く", "〜のために"),
  "during": usage("during", "介系詞，後面接名詞", "在...期間", "Please turn off phones during the meeting.", "前置詞、後ろに名詞を置く", "〜の間に"),
  "efficient": usage("efficient", "形容詞", "有效率的", "The new printer is efficient.", "形容詞", "効率的な"),
  "efficiently": usage("efficiently", "副詞", "有效率地", "The team worked efficiently.", "副詞", "効率的に"),
  "especial": usage("especial", "形容詞，較少見", "特別的", "This rule has especial importance.", "形容詞、やや古い・少ない用法", "特別な"),
  "especially": usage("especially", "副詞", "尤其／特別地", "This checklist is especially useful for new staff.", "副詞", "特に"),
  "far": usage("far", "形容詞／副詞", "遠的／遠地", "The airport is far from the hotel.", "形容詞・副詞", "遠い／遠く"),
  "farther": usage("farther", "比較級", "更遠", "The hotel is farther from the airport than the station.", "比較級", "より遠い"),
  "farthermost": usage("farthermost", "少見最高級", "最遠端的", "The farthermost cabin is rarely used.", "まれな最上級", "最も遠い"),
  "farthest": usage("farthest", "最高級", "最遠", "This store is the farthest from the station.", "最上級", "最も遠い"),
  "for": usage("for", "介系詞", "為了／持續", "This guide is for new employees.", "前置詞", "〜のために"),
  "from": usage("from", "介系詞", "從", "The desk is open from 9 a.m. to 6 p.m.", "前置詞", "〜から"),
  "high": usage("high", "形容詞", "高的", "The price is high.", "形容詞", "高い"),
  "higher": usage("higher", "比較級形容詞", "更高", "This year's sales are higher than last year's.", "比較級の形容詞", "より高い"),
  "highest": usage("highest", "最高級形容詞", "最高", "This is the highest sales total this year.", "最上級の形容詞", "最も高い"),
  "highly": usage("highly", "副詞", "非常／高度地", "The service is highly recommended.", "副詞", "非常に"),
  "hold": usage("hold", "動詞原形", "舉行／持有", "We will hold a meeting tomorrow.", "動詞の原形", "開催する／持つ"),
  "holding": usage("holding", "現在分詞／動名詞", "正在舉行／持有", "The company is holding a training session.", "現在分詞・動名詞", "開催している"),
  "holds": usage("holds", "第三人稱單數現在式", "舉行／持有", "The office holds a meeting every Tuesday.", "三人称単数の現在形", "開催する"),
  "if": usage("if", "連接詞，後面接完整句子", "如果", "Please call us if you need help.", "接続詞、後ろに文を置く", "もし〜なら"),
  "in": usage("in", "介系詞，用於月份、年份、較大空間或期間", "在...內／於", "The office opened in April.", "前置詞、月・年・広い場所に使う", "〜に／〜の中で"),
  "in case": usage("in case", "連接詞片語", "以防萬一", "Keep the receipt in case you need a refund.", "接続詞句", "万一に備えて"),
  "inspected": usage("inspected", "過去式／過去分詞", "已檢查", "The technician inspected the machine yesterday.", "過去形・過去分詞", "検査した"),
  "inspecting": usage("inspecting", "現在分詞／動名詞", "正在檢查／檢查這件事", "The technician is inspecting the machine.", "現在分詞・動名詞", "検査している"),
  "inspection": usage("inspection", "名詞", "檢查", "The inspection took one hour.", "名詞", "検査"),
  "inspects": usage("inspects", "第三人稱單數現在式", "檢查", "The technician inspects the machine every week.", "三人称単数の現在形", "検査する"),
  "instead": usage("instead", "副詞", "反而／取而代之", "The meeting was canceled, so we sent an email instead.", "副詞", "代わりに"),
  "interest": usage("interest", "名詞／動詞", "興趣／使感興趣", "Her interest in design is strong.", "名詞・動詞", "興味／興味を持たせる"),
  "interested": usage("interested", "形容詞，形容人有興趣", "感興趣的", "Interested employees should register today.", "形容詞、人の気持ちを表す", "興味がある"),
  "interesting": usage("interesting", "形容詞，形容事物令人有興趣", "有趣的", "The presentation was interesting.", "形容詞、物事の性質を表す", "興味深い"),
  "interestingly": usage("interestingly", "副詞", "有趣的是", "Interestingly, sales increased in May.", "副詞", "興味深いことに"),
  "is": usage("is", "be 動詞現在式，用於單數主詞", "是／在", "The room is clean.", "be動詞の現在形、単数主語に使う", "〜です／〜にあります"),
  "is held": usage("is held", "被動語態現在式", "被舉行", "The meeting is held every Tuesday.", "現在形の受け身", "開催される"),
  "many": usage("many", "限定詞，用於可數複數名詞", "很多", "Many employees attended the session.", "限定詞、数えられる複数名詞に使う", "多くの"),
  "more": usage("more", "比較級標記／限定詞", "更多／更", "This version is more stable than the old one.", "比較級を作る語・限定詞", "より多く／より"),
  "more efficient": usage("more efficient", "比較級形容詞片語", "更有效率", "The new printer is more efficient than the old one.", "比較級の形容詞句", "より効率的な"),
  "most": usage("most", "最高級標記／限定詞", "最多／最", "This is the most useful option.", "最上級を作る語・限定詞", "最も／ほとんどの"),
  "most efficient": usage("most efficient", "最高級形容詞片語", "最有效率", "This is the most efficient method.", "最上級の形容詞句", "最も効率的な"),
  "much": usage("much", "副詞／限定詞，用於不可數或強調比較級", "很多／更加", "This version is much faster.", "副詞・限定詞、不可算や比較級の強調に使う", "とても／ずっと"),
  "on": usage("on", "介系詞，用於日期、表面、特定搭配", "在／關於／對於", "The meeting is on Monday.", "前置詞、日付・表面・決まった表現に使う", "〜に／〜の上に"),
  "polite": usage("polite", "形容詞", "有禮貌的", "The staff member was polite.", "形容詞", "礼儀正しい"),
  "politely": usage("politely", "副詞", "有禮貌地", "She answered the call politely.", "副詞", "丁寧に"),
  "politeness": usage("politeness", "名詞", "禮貌", "Politeness is important in customer service.", "名詞", "礼儀正しさ"),
  "politer": usage("politer", "比較級形容詞，較少用，通常用 more polite", "更有禮貌", "This response is more polite than the first one.", "比較級の形容詞、通常は more polite を使う", "より礼儀正しい"),
  "postpone": usage("postpone", "動詞原形", "延期", "We may postpone the meeting.", "動詞の原形", "延期する"),
  "postponed": usage("postponed", "過去式／過去分詞", "已延期／被延期", "The meeting was postponed until Monday.", "過去形・過去分詞", "延期された"),
  "postponement": usage("postponement", "名詞", "延期", "The postponement was announced yesterday.", "名詞", "延期"),
  "postponing": usage("postponing", "現在分詞／動名詞", "正在延期／延期這件事", "The team is postponing the launch.", "現在分詞・動名詞", "延期している"),
  "practical": usage("practical", "形容詞", "實用的", "This is a practical solution.", "形容詞", "実用的な"),
  "practically": usage("practically", "副詞", "實際上／幾乎", "The task is practically finished.", "副詞", "実質的に／ほとんど"),
  "practice": usage("practice", "名詞／動詞原形", "練習／實務", "You need more practice.", "名詞・動詞の原形", "練習／練習する"),
  "practiced": usage("practiced", "過去式／過去分詞／形容詞", "練習過的／熟練的", "She is a practiced speaker.", "過去形・過去分詞・形容詞", "練習した／熟練した"),
  "preparation": usage("preparation", "名詞", "準備", "Preparation is important before a meeting.", "名詞", "準備"),
  "prepare": usage("prepare", "動詞原形", "準備", "Please prepare the report today.", "動詞の原形", "準備する"),
  "prepared": usage("prepared", "過去式／過去分詞／形容詞", "已準備／準備好的", "The report was prepared by the team.", "過去形・過去分詞・形容詞", "準備された"),
  "preparing": usage("preparing", "現在分詞／動名詞", "正在準備／準備這件事", "The team is preparing the report.", "現在分詞・動名詞", "準備している"),
  "quick": usage("quick", "形容詞", "快的", "We need a quick response.", "形容詞", "速い"),
  "quicken": usage("quicken", "動詞原形", "加快", "The update may quicken the process.", "動詞の原形", "速める"),
  "quickly": usage("quickly", "副詞", "快速地", "The team worked quickly.", "副詞", "速く"),
  "quickness": usage("quickness", "名詞", "速度／敏捷", "Her quickness helped the team.", "名詞", "速さ"),
  "reliability": usage("reliability", "名詞", "可靠性", "The reliability of the system is important.", "名詞", "信頼性"),
  "reliable": usage("reliable", "形容詞", "可靠的", "We need a reliable assistant.", "形容詞", "信頼できる"),
  "reliably": usage("reliably", "副詞", "可靠地", "The software runs reliably.", "副詞", "安定して／信頼できる形で"),
  "rely": usage("rely", "動詞原形，常用 rely on", "依靠", "We rely on accurate data.", "動詞の原形、rely on で使う", "頼る"),
  "review": usage("review", "動詞原形／名詞", "檢查／評論", "Please review the budget.", "動詞の原形・名詞", "確認する／レビュー"),
  "reviewed": usage("reviewed", "過去式／過去分詞", "已檢查", "The manager reviewed the budget yesterday.", "過去形・過去分詞", "確認した"),
  "reviewing": usage("reviewing", "現在分詞／動名詞", "正在檢查／檢查這件事", "The manager is reviewing the budget.", "現在分詞・動名詞", "確認している"),
  "reviews": usage("reviews", "第三人稱單數現在式／名詞複數", "檢查／評論", "The supervisor reviews the budget every month.", "三人称単数の現在形・名詞複数", "確認する／レビュー"),
  "since": usage("since", "連接詞／介系詞", "自從／因為", "Sales have increased since April.", "接続詞・前置詞", "〜以来／〜なので"),
  "special": usage("special", "形容詞", "特別的", "We have a special offer today.", "形容詞", "特別な"),
  "specialize": usage("specialize", "動詞原形，常用 specialize in", "專門從事", "The company specializes in software.", "動詞の原形、specialize in で使う", "専門にする"),
  "submission": usage("submission", "名詞", "提交／提交物", "The submission deadline is Friday.", "名詞", "提出／提出物"),
  "submit": usage("submit", "動詞原形", "提交", "Please submit the form by Friday.", "動詞の原形", "提出する"),
  "submitted": usage("submitted", "過去式／過去分詞", "已提交／被提交", "The form was submitted yesterday.", "過去形・過去分詞", "提出した／提出された"),
  "submitting": usage("submitting", "現在分詞／動名詞", "正在提交／提交這件事", "Submitting the form takes only a minute.", "現在分詞・動名詞", "提出している／提出すること"),
  "that": usage("that", "關係代名詞／指示詞，可指人或物", "那個／...的", "This is the form that you need to complete.", "関係代名詞・指示語、人や物に使える", "それ／〜するところの"),
  "to": usage("to", "介系詞／不定詞標記", "到／去／為了", "This software is easy to use.", "前置詞・不定詞マーカー", "〜へ／〜するために"),
  "unless": usage("unless", "連接詞，後面接完整句子", "除非", "Do not open the door unless you have permission.", "接続詞、後ろに文を置く", "〜でない限り"),
  "was": usage("was", "be 動詞過去式，用於單數主詞", "曾是／在", "The office was closed yesterday.", "be動詞の過去形、単数主語に使う", "〜でした"),
  "what": usage("what", "疑問詞／名詞子句引導詞", "什麼／...的事", "Please tell me what you need.", "疑問詞・名詞節を導く語", "何／〜すること"),
  "when": usage("when", "關係副詞／連接詞", "當...時／何時", "Please call us when you arrive.", "関係副詞・接続詞", "〜するとき"),
  "where": usage("where", "關係副詞／疑問詞", "在哪裡／...的地方", "This is where we store the files.", "関係副詞・疑問詞", "どこ／〜する場所"),
  "whether": usage("whether", "連接詞，表示是否", "是否", "The manager asked whether the invoice had been sent.", "接続詞", "〜かどうか"),
  "which": usage("which", "關係代名詞／疑問詞，通常指物", "哪一個／...的", "The printer which is near the entrance is broken.", "関係代名詞・疑問詞、物に使う", "どちら／〜するところの"),
  "while": usage("while", "連接詞，後面接完整句子", "當...期間／而", "Please wait while I check the file.", "接続詞、後ろに文を置く", "〜している間"),
  "who": usage("who", "關係代名詞／疑問詞，指人", "誰／...的人", "The employee who prepared the report is on vacation.", "関係代名詞・疑問詞、人に使う", "誰／〜する人"),
  "whose": usage("whose", "關係代名詞／疑問詞，表示所有", "誰的／其...的", "The applicant whose experience matches the job was selected.", "関係代名詞・疑問詞、所有を表す", "誰の／その人の"),
  "will be": usage("will be", "未來式 be 動詞", "將會是／將會被", "The office will be open tomorrow.", "未来の be 動詞", "〜になる／〜される"),
  "will be delivered": usage("will be delivered", "未來被動語態", "將會被送達", "The package will be delivered tomorrow.", "未来の受け身", "配達される予定"),
  "will deliver": usage("will deliver", "未來主動語態", "將會配送", "The supplier will deliver the package tomorrow.", "未来の能動態", "配達する予定"),
  "with": usage("with", "介系詞", "和／用／帶有", "Please sign the form with a pen.", "前置詞", "〜と一緒に／〜で"),
  "within": usage("within", "介系詞", "在...之內", "Customers can return items within 30 days.", "前置詞", "〜以内に")
};

export function getGrammarChoiceUsage(choice) {
  const normalizedChoice = String(choice || "").trim();
  return USAGE_BY_CHOICE[normalizedChoice] || usage(
    normalizedChoice,
    "可用英文項目，但今次句子位置不合",
    normalizedChoice,
    `Please check the correct use of "${normalizedChoice}" in a dictionary.`,
    "英語として使える表現ですが、この文の位置には合いません",
    normalizedChoice
  );
}
