const PARTS_BY_ID = {
  v001: ["noun", "verb"],
  v002: ["noun", "verb"],
  v003: ["verb"],
  v004: ["adjective"],
  v005: ["verb"],
  v006: ["noun"],
  v007: ["noun"],
  v008: ["noun"],
  v009: ["noun"],
  v010: ["noun", "verb"],
  v011: ["noun"],
  v012: ["noun"],
  v013: ["noun"],
  v014: ["noun"],
  v015: ["noun"],
  v016: ["noun"],
  v017: ["noun", "verb"],
  v018: ["noun"],
  v019: ["noun", "verb"],
  v020: ["noun"],
  v021: ["noun"],
  v022: ["noun", "verb"],
  v023: ["noun", "verb"],
  v024: ["noun", "verb"],
  v025: ["verb"],
  v026: ["verb"],
  v027: ["noun", "verb"],
  v028: ["verb"],
  v029: ["noun", "verb"],
  v030: ["verb"],
  v031: ["verb"],
  v032: ["adjective"],
  v033: ["adjective"],
  v034: ["adjective"],
  v035: ["adjective"],
  v036: ["adjective", "adverb"],
  v037: ["noun", "verb"],
  v038: ["noun", "verb"],
  v039: ["noun"],
  v040: ["noun"],
  v041: ["noun"],
  v042: ["noun"],
  v043: ["noun", "verb"],
  v044: ["noun"],
  v045: ["noun", "verb"],
  v046: ["noun", "verb"],
  v047: ["noun"],
  v048: ["noun", "verb"],
  v049: ["noun", "verb"],
  v050: ["noun"],
  v051: ["noun"],
  v052: ["noun"],
  v053: ["noun"],
  v054: ["noun"],
  v055: ["noun"],
  v056: ["noun"],
  v057: ["noun"],
  v058: ["noun", "verb"],
  v059: ["noun"],
  v060: ["noun"],
  v061: ["noun", "verb"],
  v062: ["noun", "verb"],
  v063: ["verb"],
  v064: ["verb"],
  v065: ["verb"],
  v066: ["verb"],
  v067: ["verb"],
  v068: ["verb"],
  v069: ["verb"],
  v070: ["verb"]
};

const LABELS = {
  noun: { zh: "名詞", ja: "名詞" },
  verb: { zh: "動詞", ja: "動詞" },
  adjective: { zh: "形容詞", ja: "形容詞" },
  adverb: { zh: "副詞", ja: "副詞" }
};

const WORD_FAMILIES_BY_ID = {
  v001: { noun: "invoice", verb: "invoice" },
  v002: { noun: "refund", verb: "refund", adjective: "refundable" },
  v003: { noun: "confirmation", verb: "confirm", adjective: "confirmed" },
  v004: { noun: "availability", adjective: "available" },
  v005: { noun: "submission", verb: "submit", adjective: "submitted" },
  v006: { noun: "deadline" },
  v007: { noun: "department", adjective: "departmental" },
  v008: { noun: "employee / employment", verb: "employ", adjective: "employed" },
  v009: { noun: "equipment", verb: "equip", adjective: "equipped" },
  v010: { noun: "schedule", verb: "schedule", adjective: "scheduled" },
  v011: { noun: "appointment", verb: "appoint", adjective: "appointed" },
  v012: { noun: "reservation", verb: "reserve", adjective: "reserved" },
  v013: { noun: "receipt", verb: "receive", adjective: "received" },
  v014: { noun: "expense", adjective: "expensive", adverb: "expensively" },
  v015: { noun: "policy" },
  v016: { noun: "candidate / candidacy" },
  v017: { noun: "interview", verb: "interview" },
  v018: { noun: "training", verb: "train", adjective: "trained" },
  v019: { noun: "purchase", verb: "purchase", adjective: "purchased" },
  v020: { noun: "supplier / supply", verb: "supply", adjective: "supplied" },
  v021: { noun: "shipment", verb: "ship", adjective: "shipped" },
  v022: { noun: "delay", verb: "delay", adjective: "delayed" },
  v023: { noun: "stock", verb: "stock", adjective: "stocked" },
  v024: { noun: "request", verb: "request", adjective: "requested" },
  v025: { noun: "approval", verb: "approve", adjective: "approved" },
  v026: { noun: "attachment", verb: "attach", adjective: "attached" },
  v027: { noun: "update", verb: "update", adjective: "updated" },
  v028: { noun: "announcement", verb: "announce", adjective: "announced" },
  v029: { noun: "repair", verb: "repair", adjective: "repaired" },
  v030: { noun: "replacement", verb: "replace", adjective: "replaceable / replaced" },
  v031: { noun: "maintenance", verb: "maintain", adjective: "maintained" },
  v032: { noun: "convenience", adjective: "convenient", adverb: "conveniently" },
  v033: { noun: "reliability", verb: "rely", adjective: "reliable", adverb: "reliably" },
  v034: { noun: "efficiency", adjective: "efficient", adverb: "efficiently" },
  v035: { adjective: "annual", adverb: "annually" },
  v036: { noun: "month", adjective: "monthly", adverb: "monthly" },
  v037: { noun: "contract", verb: "contract", adjective: "contractual / contracted" },
  v038: { noun: "branch", verb: "branch" },
  v039: { noun: "customer" },
  v040: { noun: "client" },
  v041: { noun: "colleague" },
  v042: { noun: "supervisor / supervision", verb: "supervise", adjective: "supervisory" },
  v043: { noun: "benefit", verb: "benefit", adjective: "beneficial", adverb: "beneficially" },
  v044: { noun: "salary", adjective: "salaried" },
  v045: { noun: "budget", verb: "budget", adjective: "budgetary / budgeted" },
  v046: { noun: "estimate", verb: "estimate", adjective: "estimated" },
  v047: { noun: "fee" },
  v048: { noun: "charge", verb: "charge", adjective: "chargeable / charged" },
  v049: { noun: "discount", verb: "discount", adjective: "discounted" },
  v050: { noun: "warranty", verb: "warrant", adjective: "warranted" },
  v051: { noun: "instruction", verb: "instruct", adjective: "instructional" },
  v052: { noun: "registration", verb: "register", adjective: "registered" },
  v053: { noun: "attendance", verb: "attend", adjective: "attended" },
  v054: { noun: "conference", verb: "confer" },
  v055: { noun: "presentation", verb: "present", adjective: "presented / presentable" },
  v056: { noun: "facility" },
  v057: { noun: "security", verb: "secure", adjective: "secure", adverb: "securely" },
  v058: { noun: "access", verb: "access", adjective: "accessible", adverb: "accessibly" },
  v059: { noun: "account / accounting", verb: "account", adjective: "accountable", adverb: "accountably" },
  v060: { noun: "password" },
  v061: { noun: "issue", verb: "issue", adjective: "issued" },
  v062: { noun: "review", verb: "review", adjective: "reviewed" },
  v063: { noun: "arrangement", verb: "arrange", adjective: "arranged" },
  v064: { noun: "delivery", verb: "deliver", adjective: "delivered" },
  v065: { noun: "notification", verb: "notify", adjective: "notified" },
  v066: { noun: "postponement", verb: "postpone", adjective: "postponed" },
  v067: { noun: "cancellation", verb: "cancel", adjective: "canceled / cancelled" },
  v068: { noun: "requirement", verb: "require", adjective: "required" },
  v069: { noun: "inclusion", verb: "include", adjective: "included / inclusive", adverb: "inclusively" },
  v070: { noun: "preparation", verb: "prepare", adjective: "prepared" }
};

export function getVocabularyParts(item) {
  return (PARTS_BY_ID[item.id] || ["word"]).map((part) => ({
    part,
    zh: LABELS[part]?.zh || "詞性",
    ja: LABELS[part]?.ja || "品詞"
  }));
}

export function getVocabularyFamily(item) {
  const family = WORD_FAMILIES_BY_ID[item.id] || {};
  return ["noun", "verb", "adjective", "adverb"].map((part) => ({
    part,
    zh: LABELS[part].zh,
    ja: LABELS[part].ja,
    form: family[part] || "-"
  }));
}
